# Generated by Django 5.2.13 on 2026-04-21 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sheets',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LogEntryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_start', models.DateField()),
                ('range_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('saved', 'Saved')], default='draft', max_length=16)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entry_runs', to='sheets.sheet')),
            ],
            options={
                'db_table': 'log_entry_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SheetRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='sheets.sheet')),
            ],
            options={
                'db_table': 'sheet_repos',
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('task', models.CharField(blank=True, max_length=512)),
                ('time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('project', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('commit_messages', models.TextField(blank=True)),
                ('raw_commits_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='sheets.logentryrun')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='sheets.sheet')),
                ('sheet_repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_entries', to='sheets.sheetrepo')),
            ],
            options={
                'db_table': 'log_entries',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='sheetrepo',
            constraint=models.UniqueConstraint(fields=('sheet', 'owner', 'name'), name='unique_sheet_owner_name'),
        ),
        migrations.AddConstraint(
            model_name='logentry',
            constraint=models.UniqueConstraint(condition=models.Q(('run__isnull', False)), fields=('run', 'sheet_repo'), name='unique_run_sheet_repo'),
        ),
    ]
